#!/usr/bin/env python

Import("env")

env.add_source_files(env.core_sources, "resources/*.cpp")
env.add_source_files(env.core_sources, "resources/shapes/*.cpp")
env.add_source_files(env.core_sources, "resources/shapes_2d/*.cpp")
#env.add_source_files(env.core_sources, "*.cpp")
