short_name = "pandemonium_engine"
name = "Pandemonium Engine"
major = 3
minor = 10
patch = 0
status = "development"
module_config = ""
year = 2022
website = "https://github.com/Relintai/pandemonium_engine"
docs = "3.4"
