FROM fedora:39

WORKDIR /root

RUN dnf -y install --setopt=install_weak_deps=False \
      bash bzip2 curl file findutils git make nano patch pkgconfig python3-pip unzip which xz yasm && \
    pip install scons==4.6.0

CMD /bin/bash
