#!/usr/bin/env python

Import("env")
Import("env_modules")

env_camera_server = env_modules.Clone()

env_camera_server.add_source_files(env.modules_sources, "register_types.cpp")
env_camera_server.add_source_files(env.modules_sources, "camera_server.cpp")
env_camera_server.add_source_files(env.modules_sources, "camera_feed.cpp")

