#!/usr/bin/env python

Import("env")

env_mlp = env.Clone()

sources = [
    "register_types.cpp",
    "code_editor.cpp",
    "script_editor_plugin.cpp",
    "script_text_editor.cpp",
    "text_editor.cpp",
    "script_editor_quick_open.cpp",
    "script_editor_base.cpp",
]

env_mlp.add_source_files(env.modules_sources, sources)
