#!/usr/bin/env python

Import("env")

env_mlp = env.Clone()

sources = [
    "register_types.cpp",

    "code_text_editor.cpp",
    "script_text_editor.cpp",
    "text_editor.cpp",
    "script_editor_base.cpp",
    "connection_info_dialog.cpp",
    "goto_line_dialog.cpp",
    "find_replace_bar.cpp",
    "script_editor_quick_open.cpp",

    "script_editor_plugin.cpp",
    "script_editor.cpp",
]

env_mlp.add_source_files(env.modules_sources, sources)
