#!/usr/bin/env python

Import("env")
Import("env_modules")

env_navigation = env_modules.Clone()

# Pandemonium source files

module_obj = []

env_navigation.add_source_files(module_obj, "*.cpp")

env.modules_sources += module_obj
