ARG img_version
FROM pandemonium-frt-base:${img_version}

RUN dpkg --add-architecture arm64 && apt-get update && apt-get install -y -q \
 crossbuild-essential-arm64

RUN apt-get install -y -q \
 libstdc++-11-dev:arm64 libsdl2-dev:arm64 libgbm-dev:arm64 libsamplerate0-dev:arm64

