ARG img_version
FROM pandemonium-fedora:${img_version}

RUN dnf -y install --setopt=install_weak_deps=False \
      gcc-c++.i686 libxcrypt-compat.i686 glibc-devel.i686 xorg-x11-server-Xvfb libX11-devel.i686 \
      libXcursor-devel.i686 libXrandr-devel.i686 libXinerama-devel.i686 libXi-devel.i686 alsa-lib-devel.i686 \
      pulseaudio-libs-devel.i686 libudev-devel mesa-libGL-devel.i686 mesa-libGLU-devel.i686 \
      mesa-dri-drivers.i686 yasm libstdc++.i686 libstdc++-static.i686

CMD /bin/bash
