name: 🤖 Android Builds
on: [push, pull_request]

# Global Settings
env:
  PANDEMONIUM_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=all debug_symbols=no werror=yes 

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  android-template:
    runs-on: "ubuntu-24.04"
    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Restore Pandemonium build cache
        uses: ./.github/actions/pandemonium-cache-restore
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/pandemonium-deps

      - name: Compilation (armv7)
        uses: ./.github/actions/pandemonium-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} android_arch=armv7
          platform: android
          target: release
          tools: false

      - name: Compilation (arm64v8)
        uses: ./.github/actions/pandemonium-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} android_arch=arm64v8
          platform: android
          target: release
          tools: false

      - name: Save Pandemonium build cache
        uses: ./.github/actions/pandemonium-cache-save
        continue-on-error: true

      - name: Generate Pandemonium templates
        run: |
          cd platform/android/java
          ./gradlew generatePandemoniumTemplates
          cd ../../..
          ls -l bin/

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
